name: Build MacOS x64 dev binary
on:
  workflow_dispatch:

jobs:
  build-test-mac-x64:
    name: Build x64 MacOS binary
    runs-on: macos-13
    steps:
      - uses: ConorMacBride/install-package@v1
        with:
          # LLVM 18 introduced incompatible change with stock libc++ [https://github.com/Homebrew/homebrew-core/issues/178435#issuecomment-2270106398]
          brew: automake llvm@17
        # force past "The `brew link` step did not complete successfully"
        continue-on-error: true
      - run: |
          if [ -f "`brew --prefix llvm`/bin/clang" ]; then
            echo "CC=`brew --prefix llvm`/bin/clang" >> $GITHUB_ENV
            echo "CXX=`brew --prefix llvm`/bin/clang++" >> $GITHUB_ENV
            echo "LDFLAGS=-L`brew --prefix llvm`/lib -Wl,-rpath,`brew --prefix llvm`/lib" >> $GITHUB_ENV
            echo "CFLAGS=-I`brew --prefix llvm`/include" >> $GITHUB_ENV
            echo "CXXFLAGS=-I`brew --prefix llvm`/include" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v3
      - run: aclocal && automake --warnings=all --add-missing && autoconf --warnings=all
      - run: ./configure
      - uses: actions/upload-artifact@v3
        with:
          path: ./config.log
          name: configure-macos-x64.log
          retention-days: 5
        if: ${{ failure() }}
      - run: make
      - run: strip par2
      - run: ./par2 -h
      - run: make check
      - run: xz -9e --x86 --lzma2 par2
      - uses: actions/upload-artifact@v3
        with:
          path: ./par2.xz
          name: par2cmdline-turbo-dev-macos-x64.xz
          retention-days: 5
